let MyMovies = [
  {
    Title: "El Diario De Anna Frank (1959)",
    IMG: "https://pics.filmaffinity.com/the_diary_of_anne_frank-697697755-large.jpg",
    Format: "MKV",
    Size: "6.2gb",
    Stored: "Asus",
  },
  {
    Title: "The Candy Shop",
    IMG: "https://m.media-amazon.com/images/M/MV5BMTMwNjM1NDI5M15BMl5BanBnXkFtZTcwNDU4OTc0NA@@._V1_FMjpg_UY11644_.jpg",
    Format: "MP4",
    Size: "686mb",
    Stored: "Asus",
  },
  {
    Title: "Buffalo Kids 2024",
    IMG: "https://pics.filmaffinity.com/buffalo_kids-634012768-large.jpg",
    Format: "MP4",
    Size: "1.4gb",
    Stored: "Asus",
  },
  {
    Title: "Hidden 2015",
    IMG: "https://pics.filmaffinity.com/hidden-832285499-large.jpg",
    Format: "MP4",
    Size: "763mb",
    Stored: "Asus",
  },
  {
    Title: "Curse Of The Sin Eater 2024",
    IMG: "https://pics.filmaffinity.com/curse_of_the_sin_eater-844287324-large.jpg",
    Format: "MP4",
    Size: "8270mb",
    Stored: "Asus",
  },
  {
    Title: "House Of Flying Daggers 2004",
    IMG: "https://pics.filmaffinity.com/shi_mian_mai_fu_house_of_flying_daggers-930841136-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "Asus",
  },
  {
    Title: "The timer traveler's Wife 2009",
    IMG: "https://pics.filmaffinity.com/the_time_traveler_s_wife-260366022-large.jpg",
    Format: "MP4",
    Size: "780mb",
    Stored: "Asus",
  },
  {
    Title: "The darkest minds 2018",
    IMG: "https://pics.filmaffinity.com/the_darkest_minds-345883539-large.jpg",
    Format: "MP4",
    Size: "891mb",
    Stored: "Asus",
  },
  {
    Title: "La vida es bella 1997",
    IMG: "https://pics.filmaffinity.com/la_vita_e_bella-646167341-large.jpg",
    Format: "AVI",
    Size: "2.6gb",
    Stored: "Asus",
  },
  {
    Title: "Waynes World 1992",
    IMG: "https://pics.filmaffinity.com/wayne_s_world-468321464-large.jpg",
    Format: "MP4",
    Size: "752mb",
    Stored: "Asus",
  },
  {
    Title: "Waynes World 2 1993",
    IMG: "https://pics.filmaffinity.com/wayne_s_world_2-114894597-large.jpg",
    Format: "MP4",
    Size: "868mb",
    Stored: "Asus",
  },
  {
    Title: "The Courier 2024",
    IMG: "https://pics.filmaffinity.com/el_correo-686123937-large.jpg",
    Format: "MP4",
    Size: "1.7gb",
    Stored: "Asus",
  },
  {
    Title: "Interstate 2024",
    IMG: "https://pics.filmaffinity.com/jour_de_colere-195765922-large.jpg",
    Format: "MP4",
    Size: "775mb",
    Stored: "Asus",
  },
  {
    Title: "Twisters 2024",
    IMG: "https://pics.filmaffinity.com/twisters-258055631-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "Asus",
  },
  {
    Title: "Jungle Book 1942",
    IMG: "https://pics.filmaffinity.com/the_jungle_book-476687037-large.jpg",
    Format: "MP4",
    Size: "811mb",
    Stored: "Asus",
  },
  {
    Title: "Politicamente incorrectos 2024",
    IMG: "https://pics.filmaffinity.com/politicamente_incorrectos-735040651-large.jpg",
    Format: "MP4",
    Size: "843mb",
    Stored: "Asus",
  },
  {
    Title: "The 7 adventures of Sinbad 2010",
    IMG: "https://m.media-amazon.com/images/M/MV5BMTY5NzEzNjg3MV5BMl5BanBnXkFtZTcwNjUxMDU3Nw@@._V1_.jpg",
    Format: "MP4",
    Size: "858mb",
    Stored: "Asus",
  },
  {
    Title: "Shaolin Prince 1982",
    IMG: "https://pics.filmaffinity.com/shaolin_chuan_ren_shaolin_prince_iron_fingers_of_death_aka_death_mask_of_the_ninja-538765351-large.jpg",
    Format: "MP4",
    Size: "853mb",
    Stored: "Asus",
  },
  {
    Title: "Borderlands 2024",
    IMG: "https://pics.filmaffinity.com/borderlands-479068097-large.jpg",
    Format: "MP4",
    Size: "925mb",
    Stored: "Asus",
  },
  {
    Title: "Superbad 2007",
    IMG: "https://pics.filmaffinity.com/superbad-543132496-large.jpg",
    Format: "MP4",
    Size: "698mb",
    Stored: "Asus",
  },
  {
    Title: "Along with the Gods-The last 49 days 2018",
    IMG: "https://pics.filmaffinity.com/singwa_hamkke_ingwa_yeon-309527284-large.jpg",
    Format: "MP4",
    Size: "1.2gb",
    Stored: "Asus",
  },
  {
    Title: "Along with the Gods-The two worlds 2017",
    IMG: "https://pics.filmaffinity.com/singwa_hamgge-415510433-large.jpg",
    Format: "MP4",
    Size: "1.2b",
    Stored: "Asus",
  },
  {
    Title: "Superman 1978",
    IMG: "https://pics.filmaffinity.com/superman_the_movie-219321225-large.jpg",
    Format: "MP4",
    Size: "1.5gb",
    Stored: "Asus",
  },
  {
    Title: "Superman II The 2006 Richard Donner Cut",
    IMG: "https://pics.filmaffinity.com/superman_ii_the_richard_donner_cut-526014301-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "Asus",
  },
  {
    Title: "A quiet place day one 2024",
    IMG: "https://pics.filmaffinity.com/a_quiet_place_day_one-758712709-large.jpg",
    Format: "MP4",
    Size: "913mb",
    Stored: "Asus",
  },
  {
    Title: "Kingdom planet Apes 2024",
    IMG: "https://pics.filmaffinity.com/kingdom_of_the_planet_of_the_apes-598062850-large.jpg",
    Format: "MP4",
    Size: "1.3gb",
    Stored: "Asus",
  },
  {
    Title: "20,000 Leagues under the sea 1954",
    IMG: "https://pics.filmaffinity.com/20_000_leagues_under_the_sea-210412348-large.jpg",
    Format: "MP4",
    Size: "913mb",
    Stored: "Asus",
  },
  {
    Title: "A night at the Roxbury 1998",
    IMG: "https://pics.filmaffinity.com/a_night_at_the_roxbury-635096001-large.jpg",
    Format: "MP4",
    Size: "752mb",
    Stored: "Asus",
  },
  {
    Title: "Beverly Hills Cop 2024",
    IMG: "https://pics.filmaffinity.com/beverly_hills_cop_axel_f-226447356-large.jpg",
    Format: "MP4",
    Size: "1.1b",
    Stored: "Asus",
  },
  {
    Title: "Despicable Me 4 2024",
    IMG: "https://pics.filmaffinity.com/despicable_me_4-802312771-large.jpg",
    Format: "MP4",
    Size: "868mb",
    Stored: "Asus",
  },
  {
    Title: "Goldbeak 2023",
    IMG: "https://pics.filmaffinity.com/goldbeak-994534069-large.jpg",
    Format: "MP4",
    Size: "830mb",
    Stored: "Asus",
  },
  {
    Title: "ID.A 2011",
    IMG: "https://pics.filmaffinity.com/id_a-886440623-large.jpg",
    Format: "MP4",
    Size: "961mb",
    Stored: "Asus",
  },
    {
    Title: "In God We Trust 1980",
    IMG: "https://pics.filmaffinity.com/in_god_we_tru_t_in_god_we_trust-374308966-large.jpg",
    Format: "MP4",
    Size: "890mb",
    Stored: "Asus",
  },
  {
    Title: "Justice League - Crisis on infinite Earth Part one 2023",
    IMG: "https://pics.filmaffinity.com/justice_league_crisis_on_infinite_earths_part_one-107214036-large.jpg",
    Format: "MP4",
    Size: "854mb",
    Stored: "Asus",
  },
  {
    Title: "Justice League - Crisis on infinite Earth Part two 2024",
    IMG: "https://pics.filmaffinity.com/justice_league_crisis_on_infinite_earths_part_two-245343293-large.jpg",
    Format: "MP4",
    Size: "872mb",
    Stored: "Asus",
  },
  {
    Title: "Justice League - Crisis on infinite Earth Part three 2024",
    IMG: "https://pics.filmaffinity.com/justice_league_crisis_on_infinite_earths_part_three-400416117-large.jpg",
    Format: "MP4",
    Size: "902mb",
    Stored: "Asus",
  },
  {
    Title: "Justice League - Crisis on Two Earths 2010",
    IMG: "https://pics.filmaffinity.com/justice_league_crisis_on_two_earths-282971079-large.jpg",
    Format: "MP4",
    Size: "692mb",
    Stored: "Asus",
  },
  {
    Title: "Los Olvidados 1950",
    IMG: "https://pics.filmaffinity.com/los_olvidados-881905768-large.jpg",
    Format: "MP4",
    Size: "743mb",
    Stored: "Asus",
  },
  {
    Title: "The American Society of Magical Negroes 2024",
    IMG: "https://pics.filmaffinity.com/the_american_society_of_magical_negroes-458586123-large.jpg",
    Format: "MP4",
    Size: "960mb",
    Stored: "Asus",
  },
  {
    Title: "The Area 51 incident 2022",
    IMG: "https://pics.filmaffinity.com/the_area_51_incident-114640602-large.jpg",
    Format: "MP4",
    Size: "753mb",
    Stored: "Asus",
  },
  {
    Title: "The fall guy 2024",
    IMG: "https://pics.filmaffinity.com/the_fall_guy-101581348-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "Asus",
  },
  {
    Title: "The last emperor 1987",
    IMG: "https://pics.filmaffinity.com/the_last_emperor-467204798-large.jpg",
    Format: "MP4",
    Size: "1.8gb",
    Stored: "Asus",
  },
  {
    Title: "The light at the edge of the world 1971",
    IMG: "https://pics.filmaffinity.com/the_light_at_the_edge_of_the_world-202645273-large.jpg",
    Format: "MP4",
    Size: "1.2gb",
    Stored: "Asus",
  },
  {
    Title: "The Youtube Effect 2022",
    IMG: "https://pics.filmaffinity.com/the_youtube_effect-745820740-large.jpg",
    Format: "MP4",
    Size: "914mb",
    Stored: "Asus",
  },
  {
    Title: "Watchmen Chapter I 2024",
    IMG: "https://pics.filmaffinity.com/watchmen_chapter_i-752056811-large.jpg",
    Format: "MP4",
    Size: "771mb",
    Stored: "Asus",
  },
  {
    Title: "Sound of freedom 2023",
    IMG: "https://pics.filmaffinity.com/sound_of_freedom-546775358-large.jpg",
    Format: "MP4",
    Size: "1.2gb",
    Stored: "Asus",
  },
  {
    Title: "Renfield 2023",
    IMG: "https://pics.filmaffinity.com/renfield-758566468-large.jpg",
    Format: "MP4",
    Size: "862mb",
    Stored: "Asus",
  },
  {
    Title: "Fearless 2006",
    IMG: "https://pics.filmaffinity.com/huo_yuan_jia_aka_huo_yuanjia_fearless-632665125-large.jpg",
    Format: "MP4",
    Size: "1.2gb",
    Stored: "Asus",
  },
  {
    Title: "Gunpowder Milkshake 2021",
    IMG: "https://pics.filmaffinity.com/gunpowder_milkshake-287339808-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "Asus",
  },
  {
    Title: "Inside Out 2 2024",
    IMG: "https://pics.filmaffinity.com/inside_out_2-365634749-large.jpg",
    Format: "MP4",
    Size: "886mb",
    Stored: "Asus",
  },
  {
    Title: "The pianist 2002",
    IMG: "https://pics.filmaffinity.com/the_pianist_le_pianiste-978132965-large.jpg",
    Format: "MKV",
    Size: "899mb",
    Stored: "Asus",
  },
  {
    Title: "Bad Boys 1995",
    IMG: "https://pics.filmaffinity.com/bad_boys-129541367-large.jpg",
    Format: "MKV",
    Size: "550mb",
    Stored: "Asus",
  },
  {
    Title: "Bad Boys For Life 2020",
    IMG: "https://pics.filmaffinity.com/bad_boys_for_life-343590773-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "Asus",
  },
  {
    Title: "Bad Boys II 2003",
    IMG: "https://pics.filmaffinity.com/bad_boys_ii-516511431-large.jpg",
    Format: "MP4",
    Size: "850mb",
    Stored: "Asus",
  },
  {
    Title: "Bad Boys Ride or Die 2024",
    IMG: "https://pics.filmaffinity.com/bad_boys_ride_or_die-651037313-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "Asus",
  },
  {
    Title: "Mavka The Forest Song 2023",
    IMG: "https://pics.filmaffinity.com/mavka_the_forest_song-447812217-large.jpg",
    Format: "MP4",
    Size: "919mb",
    Stored: "Asus",
  },
  {
    Title: "Riley First Date 2015",
    IMG: "https://pics.filmaffinity.com/riley_s_first_date_aka_inside_out_riley_s_first_date-711927690-large.jpg",
    Format: "MP4",
    Size: "40mb",
    Stored: "Asus",
  },
  {
    Title: "Predator Dark Ages 2015",
    IMG: "https://pics.filmaffinity.com/predator_dark_ages_s-186900871-large.jpg",
    Format: "MP4",
    Size: "141mb",
    Stored: "Asus",
  },
  {
    Title: "Twister 1996",
    IMG: "https://pics.filmaffinity.com/twister-707246974-large.jpg",
    Format: "MP4",
    Size: "750mb",
    Stored: "Asus",
  },
  {
    Title: "The Terminal 2004",
    IMG: "https://pics.filmaffinity.com/the_terminal-810140451-large.jpg",
    Format: "MP4",
    Size: "875mb",
    Stored: "Asus",
  },
  {
    Title: "Dante's Inferno 2010",
    IMG: "https://pics.filmaffinity.com/dante_s_inferno-870650914-large.jpg",
    Format: "MP4",
    Size: "757mb",
    Stored: "Asus",
  },
  {
    Title: "Village of the Damned 1960",
    IMG: "https://pics.filmaffinity.com/village_of_the_damned-694827428-large.jpg",
    Format: "MP4",
    Size: "625mb",
    Stored: "Asus",
  },
  {
    Title: "Yo antes de ti 2016",
    IMG: "https://pics.filmaffinity.com/me_before_you-594538815-large.jpg",
    Format: "MKV",
    Size: "1.1gb",
    Stored: "Asus",
  },
  {
    Title: "They Live 1988",
    IMG: "https://pics.filmaffinity.com/they_live_aka_john_carpenter_s_they_live-382338340-large.jpg",
    Format: "MP4",
    Size: "753mb",
    Stored: "Asus",
  },
  {
    Title: "The Count of montecristo 1975",
    IMG: "https://pics.filmaffinity.com/the_count_of_monte_cristo_tv-431091968-large.jpg",
    Format: "MP4",
    Size: "949mb",
    Stored: "Asus",
  },
  {
    Title: "Not another Church movie 2024",
    IMG: "https://pics.filmaffinity.com/not_another_church_movie-810770632-large.jpg",
    Format: "MP4",
    Size: "832mb",
    Stored: "Asus",
  },
  {
    Title: "IF 2024",
    IMG: "https://pics.filmaffinity.com/if-160232365-large.jpg",
    Format: "MP4",
    Size: "1.8gb",
    Stored: "Asus",
  },
  {
    Title: "57 Seconds 2023",
    IMG: "https://pics.filmaffinity.com/57_seconds-102208376-large.jpg",
    Format: "MP4",
    Size: "915mb",
    Stored: "Asus",
  },
  {
    Title: "17 Again 2009",
    IMG: "https://pics.filmaffinity.com/17_again-107120789-large.jpg",
    Format: "MP4",
    Size: "650mb",
    Stored: "Asus",
  },
  {
    Title: "The Pink Panther 2 2009",
    IMG: "https://pics.filmaffinity.com/the_pink_panther_2-251520555-large.jpg",
    Format: "MP4",
    Size: "650mb",
    Stored: "Asus",
  },
  {
    Title: "The Pink Panther 2006",
    IMG: "https://pics.filmaffinity.com/the_pink_panther-898050283-large.jpg",
    Format: "MP4",
    Size: "750mb",
    Stored: "Asus",
  },
  {
    Title: "My stepmother is an alien 1988",
    IMG: "https://pics.filmaffinity.com/my_stepmother_is_an_alien-929465450-large.jpg",
    Format: "MP4",
    Size: "991mb",
    Stored: "Asus",
  },
  {
    Title: "Idiocracy 2006",
    IMG: "https://pics.filmaffinity.com/idiocracy-910754497-large.jpg",
    Format: "MP4",
    Size: "551mb",
    Stored: "Asus",
  },
  {
    Title: "Nanquan zhi Yingxiong jue qi (Heroes) 2020",
    IMG: "https://m.media-amazon.com/images/M/MV5BNmRlZjM3MzMtN2NmOS00M2NmLWFjMzEtOTA2MmIzZGU1N2QwXkEyXkFqcGc@._V1_FMjpg_UX810_.jpg",
    Format: "MKV",
    Size: "1.4gb",
    Stored: "Asus",
  },
  {
    Title: "The Abyss 1989",
    IMG: "https://pics.filmaffinity.com/the_abyss-583638777-large.jpg",
    Format: "ISO",
    Size: "4.1gb",
    Stored: "Legacy",
  },
  {
    Title: "The Abyss 1989",
    IMG: "https://pics.filmaffinity.com/the_abyss-583638777-large.jpg",
    Format: "MP4",
    Size: "1.5gb",
    Stored: "Legacy",
  },
  {
    Title: "Enrique y Ana 1981",
    IMG: "https://pics.filmaffinity.com/las_aventuras_de_enrique_y_ana-261876533-large.jpg",
    Format: "ISO",
    Size: "4.1gb",
    Stored: "Legacy",
  },
  {
    Title: "Excision 2012",
    IMG: "https://pics.filmaffinity.com/excision-335151662-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Hitler 1977",
    IMG: "http://pics.filmaffinity.com/hitler_eine_karriere_hitler_a_career-222682789-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Hitler 1977",
    IMG: "http://pics.filmaffinity.com/hitler_eine_karriere_hitler_a_career-222682789-large.jpg",
    Format: "MP4",
    Size: "1.4gb",
    Stored: "Legacy",
  },
  {
    Title: "Padre no hay mas que uno 1 2019",
    IMG: "https://pics.filmaffinity.com/padre_no_hay_mas_que_uno-289733769-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "The Saint 1997",
    IMG: "https://pics.filmaffinity.com/the_saint-800520925-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "SuperGirl 1984",
    IMG: "https://pics.filmaffinity.com/supergirl-835655094-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "RoboCop 1 1987",
    IMG: "https://pics.filmaffinity.com/robocop-178512372-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "RoboCop 2 1990",
    IMG: "https://pics.filmaffinity.com/robocop_2-768486049-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "RoboCop 3 1993",
    IMG: "https://pics.filmaffinity.com/robocop_3-758520258-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Gremlims 1 1984",
    IMG: "https://pics.filmaffinity.com/gremlins-305336656-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Gremlims 2 1990",
    IMG: "https://pics.filmaffinity.com/gremlins_2_the_new_batch-645513601-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Kiki 2016",
    IMG: "https://pics.filmaffinity.com/kiki_el_amor_se_hace-949639720-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "Tacones Lejanos 1991",
    IMG: "https://pics.filmaffinity.com/tacones_lejanos-553473811-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "The children of a Lesser God 1986",
    IMG: "https://pics.filmaffinity.com/children_of_a_lesser_god-516650797-large.jpg",
    Format: "ISO",
    Size: "4.2gb",
    Stored: "Legacy",
  },
  {
    Title: "The Truman Show 1998",
    IMG: "https://pics.filmaffinity.com/the_truman_show-130091557-large.jpg",
    Format: "MP4",
    Size: "1.6gb",
    Stored: "External",
  },
  {
    Title: "Uncharted 2022",
    IMG: "https://pics.filmaffinity.com/uncharted-417211360-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "007 Casino Royale 2005",
    IMG: "https://pics.filmaffinity.com/casino_royale-126696965-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "007 Die Another Day 2002",
    IMG: "https://pics.filmaffinity.com/die_another_day-987805254-large.jpg",
    Format: "MP4",
    Size: "949mb",
    Stored: "External",
  },
  {
    Title: "007 Golden Eye 1995",
    IMG: "https://pics.filmaffinity.com/tina_turner_goldeneye-575367065-large.jpg",
    Format: "MP4",
    Size: "949mb",
    Stored: "External",
  },
  {
    Title: "007 License to kill 1989",
    IMG: "https://m.media-amazon.com/images/M/MV5BYjY3OWJkMjMtYTgwYS00MjJjLWE4M2ItOWVhOWMxNGM1NDk3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    Format: "MP4",
    Size: "950mb",
    Stored: "External",
  },
  {
    Title: "007 Never say never again 1983",
    IMG: "https://pics.filmaffinity.com/never_say_never_again-910893909-large.jpg",
    Format: "MP4",
    Size: "950mb",
    Stored: "External",
  },
  {
    Title: "007 Quantum of Solace 2008",
    IMG: "https://pics.filmaffinity.com/quantum_of_solace-911955696-large.jpg",
    Format: "MP4",
    Size: "799mb",
    Stored: "External",
  },
  {
    Title: "007 The living daylights 1987",
    IMG: "https://m.media-amazon.com/images/M/MV5BZjI4MjBmYzItYTY5OC00OWYzLWE0NWYtZDQxNDQxM2QzYjA4XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_FMjpg_UX1000_.jpg",
    Format: "MP4",
    Size: "949mb",
    Stored: "External",
  },
  {
    Title: "007 The world is not enough 1999",
    IMG: "https://pics.filmaffinity.com/the_world_is_not_enough-296126975-large.jpg",
    Format: "MP4",
    Size: "949mb",
    Stored: "External",
  },
  {
    Title: "007 Tomorrow never dies 1997",
    IMG: "https://pics.filmaffinity.com/tomorrow_never_dies-493956113-large.jpg",
    Format: "MP4",
    Size: "899mb",
    Stored: "External",
  },
  {
    Title: "007 No timer to die 2021",
    IMG: "https://pics.filmaffinity.com/no_time_to_die-525355918-large.jpg",
    Format: "MP4",
    Size: "1.5gb",
    Stored: "External",
  },
  {
    Title: "007 Skyfall 2012",
    IMG: "https://pics.filmaffinity.com/skyfall-387366879-large.jpg",
    Format: "MP4",
    Size: "950mb",
    Stored: "External",
  },
  {
    Title: "007 Spectre 2015",
    IMG: "https://pics.filmaffinity.com/spectre-683709494-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "12 Monkeys 1995",
    IMG: "https://pics.filmaffinity.com/twelve_monkeys_12_monkeys-969079026-large.jpg",
    Format: "MP4",
    Size: "752mb",
    Stored: "External",
  },
  {
    Title: "1492 Conquest of Paradise 1992",
    IMG: "https://pics.filmaffinity.com/1492_the_conquest_of_paradise-206564879-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "2047 Virtual Revolution 2016",
    IMG: "https://pics.filmaffinity.com/virtual_revolution-460157529-large.jpg",
    Format: "MP4",
    Size: "849mb",
    Stored: "External",
  },
  {
    Title: "2067 2020",
    IMG: "https://pics.filmaffinity.com/2067-585488368-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "300 2006",
    IMG: "https://pics.filmaffinity.com/300-177205452-large.jpg",
    Format: "MP4",
    Size: "752mb",
    Stored: "External",
  },
  {
    Title: "300 Rise of an Empire 2014",
    IMG: "https://pics.filmaffinity.com/300_rise_of_an_empire-579288813-large.jpg",
    Format: "MP4",
    Size: "808mb",
    Stored: "External",
  },
  {
    Title: "3096 Tage 2013",
    IMG: "https://pics.filmaffinity.com/3096_tage_kampusch-143101249-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "8 Mile 2002",
    IMG: "https://pics.filmaffinity.com/8_mile-229373133-large.jpg",
    Format: "MKV",
    Size: "597mb",
    Stored: "External",
  },
  {
    Title: "8-bit Christmas 2021",
    IMG: "https://pics.filmaffinity.com/8_bit_christmas-519289413-large.jpg",
    Format: "MP4",
    Size: "897mb",
    Stored: "External",
  },
  {
    Title: "9 2009",
    IMG: "https://pics.filmaffinity.com/9-530356351-large.jpg",
    Format: "MP4",
    Size: "694mb",
    Stored: "External",
  },
  {
    Title: "A million ways to die in the west 2014",
    IMG: "https://pics.filmaffinity.com/a_million_ways_to_die_in_the_west-805416013-large.jpg",
    Format: "MP4",
    Size: "818mb",
    Stored: "External",
  },
  {
    Title: "A not so merry Christmas 2022",
    IMG: "https://pics.filmaffinity.com/reviviendo_la_navidad-915488874-large.jpg",
    Format: "MP4",
    Size: "922mb",
    Stored: "External",
  },
  {
    Title: "A promise of time travel 2016",
    IMG: "https://m.media-amazon.com/images/M/MV5BZTUzOTc0YWYtODI0Ny00YjUzLTgxODgtMGVhYTc5NDFkMmFmXkEyXkFqcGdeQXVyMTE1OTI2MzAw._V1_FMjpg_UX1000_.jpg",
    Format: "MP4",
    Size: "808mb",
    Stored: "External",
  },
  {
    Title: "A-X-L 2018",
    IMG: "https://pics.filmaffinity.com/a_x_l-397045963-large.jpg",
    Format: "MP4",
    Size: "851mb",
    Stored: "External",
  },
  {
    Title: "A.I. Rising 2018",
    IMG: "https://pics.filmaffinity.com/ederlezi_rising-511055563-large.jpg",
    Format: "MP4",
    Size: "755mb",
    Stored: "External",
  },
  {
    Title: "Abigail 2019",
    IMG: "https://pics.filmaffinity.com/abigail-660346492-large.jpg",
    Format: "MP4",
    Size: "960mb",
    Stored: "External",
  },
  {
    Title: "After Life 2009",
    IMG: "https://pics.filmaffinity.com/after_life_afterlife-931936129-large.jpg",
    Format: "MP4",
    Size: "1.5gb",
    Stored: "External",
  },
  {
    Title: "Agent Game 2022",
    IMG: "https://pics.filmaffinity.com/agent_game-246632697-large.jpg",
    Format: "MP4",
    Size: "827mb",
    Stored: "External",
  },
  {
    Title: "Air Force One 1997",
    IMG: "https://pics.filmaffinity.com/air_force_one-366551683-large.jpg",
    Format: "MP4",
    Size: "800mb",
    Stored: "External",
  },
  {
    Title: "Air Force One Down 2024",
    IMG: "https://pics.filmaffinity.com/air_force_one_down-229790625-large.jpg",
    Format: "MP4",
    Size: "804mb",
    Stored: "External",
  },
  {
    Title: "Airheads 1994",
    IMG: "https://pics.filmaffinity.com/airheads-735509305-large.jpg",
    Format: "MP4",
    Size: "789mb",
    Stored: "External",
  },
  {
    Title: "Airplane 1980",
    IMG: "https://pics.filmaffinity.com/airplane-343976645-large.jpg",
    Format: "MP4",
    Size: "769mb",
    Stored: "External",
  },
  {
    Title: "Airplane II The sequel 1982",
    IMG: "https://pics.filmaffinity.com/airplane_ii_the_sequel-846915353-large.jpg",
    Format: "MP4",
    Size: "774mb",
    Stored: "External",
  },
  {
    Title: "Akira 1988",
    IMG: "https://pics.filmaffinity.com/akira-262742931-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "Aladdin 1992",
    IMG: "https://pics.filmaffinity.com/aladdin-819103562-large.jpg",
    Format: "MP4",
    Size: "650mb",
    Stored: "External",
  },
  {
    Title: "Aladdin 2019",
    IMG: "https://pics.filmaffinity.com/aladdin-443262605-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "Aladdin and The King of Thieves 1996",
    IMG: "https://pics.filmaffinity.com/aladdin_and_the_king_of_thieves-477752056-large.jpg",
    Format: "MP4",
    Size: "695mb",
    Stored: "External",
  },
  {
    Title: "The Return of Jafar 1994",
    IMG: "https://pics.filmaffinity.com/the_return_of_jafar-342140394-large.jpg",
    Format: "MP4",
    Size: "512mb",
    Stored: "External",
  },
  {
    Title: "Alien Addiction 2018",
    IMG: "https://pics.filmaffinity.com/alien_addiction-537771200-large.jpg",
    Format: "MP4",
    Size: "891mb",
    Stored: "External",
  },
  {
    Title: "Alien Predator 2018",
    IMG: "https://pics.filmaffinity.com/alien_predator-777676204-large.jpg",
    Format: "MP4",
    Size: "750mb",
    Stored: "External",
  },
  {
    Title: "Alien 1979",
    IMG: "https://pics.filmaffinity.com/alien-657278575-large.jpg",
    Format: "AVI",
    Size: "700mb",
    Stored: "External",
  },
  {
    Title: "Alien 2 1986",
    IMG: "https://pics.filmaffinity.com/aliens-989223912-large.jpg",
    Format: "AVI",
    Size: "901mb",
    Stored: "External",
  },
  {
    Title: "Alien 3 1992",
    IMG: "https://pics.filmaffinity.com/alien3-521432773-large.jpg",
    Format: "AVI",
    Size: "700mb",
    Stored: "External",
  },
  {
    Title: "Alien Resurrection 1997",
    IMG: "https://pics.filmaffinity.com/alien_resurrection-257654592-large.jpg",
    Format: "AVI",
    Size: "701mb",
    Stored: "External",
  },
  {
    Title: "Alien Covenant 2017",
    IMG: "https://pics.filmaffinity.com/alien_covenant-271063602-large.jpg",
    Format: "MP4",
    Size: "916mb",
    Stored: "External",
  },
  {
    Title: "Aliens stole my body 2020",
    IMG: "https://pics.filmaffinity.com/aliens_stole_my_body-620869472-large.jpg",
    Format: "MP4",
    Size: "809mb",
    Stored: "External",
  },
  {
    Title: "Alita batle angel 2019",
    IMG: "https://pics.filmaffinity.com/alita_battle_angel-715028190-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "Alive 1993",
    IMG: "https://pics.filmaffinity.com/alive-107560352-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "Alligator 1980",
    IMG: "https://pics.filmaffinity.com/alligator-921524767-large.jpg",
    Format: "MP4",
    Size: "799mb",
    Stored: "External",
  },
  {
    Title: "Alvin & the chipmunks chipwrecked2011",
    IMG: "https://pics.filmaffinity.com/alvin_and_the_chipmunks_chip_wrecked_alvin_and_the_chipmunks_3-832384115-large.jpg",
    Format: "MP4",
    Size: "599mb",
    Stored: "External",
  },
  {
    Title: "An american pickle 2020",
    IMG: "https://pics.filmaffinity.com/an_american_pickle-705096871-large.jpg",
    Format: "MP4",
    Size: "811mb",
    Stored: "External",
  },
  {
    Title: "Analyze this 1999",
    IMG: "https://pics.filmaffinity.com/analyze_this-381458535-large.jpg",
    Format: "MP4",
    Size: "950mb",
    Stored: "External",
  },
  {
    Title: "Analyze that 2002",
    IMG: "https://pics.filmaffinity.com/analyze_that-742677339-large.jpg",
    Format: "MP4",
    Size: "696mb",
    Stored: "External",
  },
  {
    Title: "Andhadhun 2018",
    IMG: "https://pics.filmaffinity.com/andhadhun-559263845-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "Angels & Demons 2009",
    IMG: "https://pics.filmaffinity.com/angels_demons-758086263-large.jpg",
    Format: "MKV",
    Size: "1.3gb",
    Stored: "External",
  },
  {
    Title: "Anna and the king 1999",
    IMG: "https://pics.filmaffinity.com/anna_and_the_king-362588501-large.jpg",
    Format: "MP4",
    Size: "1.3gb",
    Stored: "External",
  },
  {
    Title: "Annabelle creation 2017",
    IMG: "https://pics.filmaffinity.com/annabelle_creation-692576203-large.jpg",
    Format: "MP4",
    Size: "801mb",
    Stored: "External",
  },
  {
    Title: "Anne of Green Gables 1934",
    IMG: "https://pics.filmaffinity.com/anne_of_green_gables-977583018-large.jpg",
    Format: "MP4",
    Size: "687mb",
    Stored: "External",
  },
  {
    Title: "Anne of Green Gables New Beginning 2008",
    IMG: "https://pics.filmaffinity.com/anne_of_green_gables_a_new_beginning_tv-994421789-large.jpg",
    Format: "MP4",
    Size: "1.3gb",
    Stored: "External",
  },
  {
    Title: "Anne of Green Gables 2016",
    IMG: "https://pics.filmaffinity.com/anne_of_green_gables-339712617-large.jpg",
    Format: "MP4",
    Size: "871mb",
    Stored: "External",
  },
  {
    Title: "Anon 2018",
    IMG: "https://pics.filmaffinity.com/anon-560043843-large.jpg",
    Format: "MP4",
    Size: "844mb",
    Stored: "External",
  },
  {
    Title: "Ape vs Monster 2021",
    IMG: "https://pics.filmaffinity.com/ape_vs_monster-667025190-large.jpg",
    Format: "MP4",
    Size: "809mb",
    Stored: "External",
  },
  {
    Title: "Apocalypto 2006",
    IMG: "https://pics.filmaffinity.com/apocalypto-732074347-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "Arachnofobia 1990",
    IMG: "https://pics.filmaffinity.com/arachnophobia-585444133-large.jpg",
    Format: "MP4",
    Size: "751mb",
    Stored: "External",
  },
  {
    Title: "Army of one 2016",
    IMG: "https://pics.filmaffinity.com/army_of_one-998726633-large.jpg",
    Format: "MP4",
    Size: "663mb",
    Stored: "External",
  },
  {
    Title: "ARQ 2016",
    IMG: "https://pics.filmaffinity.com/arq-692316640-large.jpg",
    Format: "MP4",
    Size: "801mb",
    Stored: "External",
  },
  {
    Title: "Arrival 2016",
    IMG: "https://pics.filmaffinity.com/arrival-150207636-large.jpg",
    Format: "MKV",
    Size: "952mb",
    Stored: "External",
  },
  {
    Title: "Assassin 33 A.D. 2020",
    IMG: "https://pics.filmaffinity.com/assassin_33_a_d-203910020-large.jpg",
    Format: "MP4",
    Size: "995mb",
    Stored: "External",
  },
  {
    Title: "Assassin Club 2023",
    IMG: "https://pics.filmaffinity.com/assassin_club-144391449-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "At the Earth's Core 1976",
    IMG: "https://pics.filmaffinity.com/at_the_earth_s_core-216049963-large.jpg",
    Format: "MP4",
    Size: "701mb",
    Stored: "External",
  },
  {
    Title: "Atlantic Rim 2 2018",
    IMG: "https://pics.filmaffinity.com/atlantic_rim_resurrection-721413094-large.jpg",
    Format: "MP4",
    Size: "735mb",
    Stored: "External",
  },
  {
    Title: "Pacific Rim 2013",
    IMG: "https://pics.filmaffinity.com/pacific_rim-524748435-large.jpg",
    Format: "MP4",
    Size: "1.9gb",
    Stored: "External",
  },
  {
    Title: "Pacific Rim 2 2018",
    IMG: "https://pics.filmaffinity.com/pacific_rim_uprising-309443835-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "Atlas 2024",
    IMG: "https://pics.filmaffinity.com/atlas-570877983-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
  {
    Title: "Attack on Titan 2015",
    IMG: "https://pics.filmaffinity.com/shingeki_no_kyojin_zenpen_attack_on_titan_the_movie-821975853-large.jpg",
    Format: "MP4",
    Size: "852mb",
    Stored: "External",
  },
  {
    Title: "Attack on Titan 2 2015",
    IMG: "https://pics.filmaffinity.com/shingeki_no_kyojin_kouhen_attack_on_titan_2_end_of_the_world-892262136-large.jpg",
    Format: "MKV",
    Size: "700mb",
    Stored: "External",
  },
  {
    Title: "Avatar 2009",
    IMG: "https://pics.filmaffinity.com/avatar-208925608-large.jpg",
    Format: "MP4",
    Size: "1.6gb",
    Stored: "External",
  },
  {
    Title: "Avatar The way of water 2022",
    IMG: "https://pics.filmaffinity.com/avatar_the_way_of_water-722646748-large.jpg",
    Format: "MP4",
    Size: "1.7gb",
    Stored: "External",
  },
  {
    Title: "Babysitting 2014",
    IMG: "https://pics.filmaffinity.com/babysitting-661690405-large.jpg",
    Format: "MP4",
    Size: "741mb",
    Stored: "External",
  },
  {
    Title: "Bad Teacher 2011",
    IMG: "https://pics.filmaffinity.com/bad_teacher-569182694-large.jpg",
    Format: "MP4",
    Size: "649mb",
    Stored: "External",
  },
  {
    Title: "Bad times at the El Royale 2018",
    IMG: "https://pics.filmaffinity.com/bad_times_at_the_el_royale-475353164-large.jpg",
    Format: "MP4",
    Size: "1.2gb",
    Stored: "External",
  },
  {
    Title: "Barbie 2023",
    IMG: "https://pics.filmaffinity.com/barbie-295661697-large.jpg",
    Format: "MP4",
    Size: "1gb",
    Stored: "External",
  },
  {
    Title: "Battleship 2012",
    IMG: "https://pics.filmaffinity.com/battleship-892064806-large.jpg",
    Format: "MP4",
    Size: "850mb",
    Stored: "External",
  },
  {
    Title: "Be kind, rewind 2008",
    IMG: "https://pics.filmaffinity.com/be_kind_rewind-314899315-large.jpg",
    Format: "MP4",
    Size: "701mb",
    Stored: "External",
  },
  {
    Title: "Beauty and the Beast 1991",
    IMG: "https://pics.filmaffinity.com/beauty_and_the_beast-152980110-large.jpg",
    Format: "MP4",
    Size: "549mb",
    Stored: "External",
  },
  {
    Title: "Batman and Harley Quinn 2017",
    IMG: "https://pics.filmaffinity.com/batman_and_harley_quinn-695683921-large.jpg",
    Format: "MP4",
    Size: "548mb",
    Stored: "External",
  },
  {
    Title: "Batman and Superman Battle of SuperSons 2022",
    IMG: "https://pics.filmaffinity.com/batman_and_superman_battle_of_the_super_sons-786314036-large.jpg",
    Format: "MP4",
    Size: "730mb",
    Stored: "External",
  },
  {
    Title: "Batman Bad Blood 2016",
    IMG: "https://pics.filmaffinity.com/batman_bad_blood-385216736-large.jpg",
    Format: "MP4",
    Size: "543mb",
    Stored: "External",
  },
  {
    Title: "Batman Ninja 2018",
    IMG: "https://pics.filmaffinity.com/batman_ninja-215402428-large.jpg",
    Format: "MP4",
    Size: "729mb",
    Stored: "External",
  },
  {
    Title: "Batman The Dark Knight Returns 1 2012",
    IMG: "https://pics.filmaffinity.com/batman_the_dark_knight_returns_part_1-196334814-large.jpg",
    Format: "MP4",
    Size: "500mb",
    Stored: "External",
  },
  {
    Title: "Batman The Dark Knight Returns 2 2013",
    IMG: "https://pics.filmaffinity.com/batman_the_dark_knight_returns_part_2-892522096-large.jpg",
    Format: "MP4",
    Size: "599mb",
    Stored: "External",
  },
  {
    Title: "Batman The Doom that came to Gotham 2023",
    IMG: "https://pics.filmaffinity.com/batman_the_doom_that_came_to_gotham-818271390-large.jpg",
    Format: "MP4",
    Size: "794mb",
    Stored: "External",
  },
  {
    Title: "Batman the killing joke 2016",
    IMG: "https://pics.filmaffinity.com/batman_the_killing_joke-179887395-large.jpg",
    Format: "MP4",
    Size: "566mb",
    Stored: "External",
  },
  {
    Title: "Batman the long halloween 2 2021",
    IMG: "https://pics.filmaffinity.com/batman_the_long_halloween_part_two-673488853-large.jpg",
    Format: "MP4",
    Size: "800mb",
    Stored: "External",
  },
  {
    Title: "Batman under the red hood 2010",
    IMG: "https://pics.filmaffinity.com/batman_under_the_red_hood-848172539-large.jpg",
    Format: "MP4",
    Size: "550mb",
    Stored: "External",
  },
  {
    Title: "Batman vs Superman Dawn of Justice 2016",
    IMG: "https://pics.filmaffinity.com/batman_v_superman_dawn_of_justice-728293826-large.jpg",
    Format: "AVI",
    Size: "698mb",
    Stored: "External",
  },
  {
    Title: "Batman year one 2011",
    IMG: "https://pics.filmaffinity.com/batman_year_one-374806605-large.jpg",
    Format: "MP4",
    Size: "252mb",
    Stored: "External",
  },
  {
    Title: "Catwoman Hunted 2022",
    IMG: "https://pics.filmaffinity.com/catwoman_hunted-612802354-large.jpg",
    Format: "MP4",
    Size: "724mb",
    Stored: "External",
  },
  {
    Title: "Son of Batman 2014",
    IMG: "https://pics.filmaffinity.com/son_of_batman-492992831-large.jpg",
    Format: "AVI",
    Size: "698mb",
    Stored: "External",
  },
  {
    Title: "Batman 2022",
    IMG: "https://pics.filmaffinity.com/the_batman-449856406-large.jpg",
    Format: "MP4",
    Size: "1.6gb",
    Stored: "External",
  },
  {
    Title: "The Dark Knight Rises 2012",
    IMG: "https://pics.filmaffinity.com/the_dark_knight_rises-149544881-large.jpg",
    Format: "MP4",
    Size: "1.1gb",
    Stored: "External",
  },
];
//me quede en beauty and the beast 2017
//{Title:"",IMG:"",Format:"MP4",Size:"mb",Stored:"Legacy",},
//{Title:"",IMG:"",Format:"MP4",Size:"mb",Stored:"Asus",},
//{Title:"",IMG:"",Format:"MP4",Size:"mb",Stored:"External",},
